build:
  version: 2016-03-14 # version of the build schema.
  steps:
    # Platform: Drupal
    # Variant: Acquia
    drupal-acquia-httpd:
      name: _env(PREFIX)drupal-acquia-httpd:_env(TAG)
      context: drupal/acquia/httpd
      dockerfile: Dockerfile
    drupal-acquia-mysql:
      name: _env(PREFIX)drupal-acquia-mysql:_env(TAG)
      context: drupal/acquia/mysql
      dockerfile: Dockerfile
    drupal-acquia-php-7.1:
      name: _env(PREFIX)drupal-acquia-php-7.1:_env(TAG)
      context: drupal/acquia/php
      dockerfile: Dockerfile
      args:
        version: 7.1
    drupal-acquia-php-7.2:
      name: _env(PREFIX)drupal-acquia-php-7.2:_env(TAG)
      context: drupal/acquia/php
      dockerfile: Dockerfile
      args:
        version: 7.2
      depends_on:
        # Ensure serial build
        - drupal-acquia-php-7.1
    # Variant: Pantheon
    drupal-pantheon-nginx:
      name: _env(PREFIX)drupal-pantheon-nginx:_env(TAG)
      context: drupal/pantheon/nginx
      dockerfile: Dockerfile
    drupal-pantheon-mysql:
      name: _env(PREFIX)drupal-pantheon-mysql:_env(TAG)
      context: drupal/pantheon/mysql
      dockerfile: Dockerfile
    drupal-pantheon-php-7.1:
      name: _env(PREFIX)drupal-pantheon-php-7.1:_env(TAG)
      context: drupal/pantheon/php
      dockerfile: Dockerfile
      args:
        version: 7.1
    drupal-pantheon-php-7.2:
      name: _env(PREFIX)drupal-pantheon-php-7.2:_env(TAG)
      context: drupal/pantheon/php
      dockerfile: Dockerfile
      args:
        version: 7.2
      depends_on:
        - drupal-pantheon-php-7.1
    ## Platform: Baseline7
    # Variant: CentOS DISA STIG
    baseline7-centos-disa:
      name: _env(PREFIX)baseline7-centos-disa:_env(TAG)
      context: baselines/baseline7
      dockerfile: Dockerfile
      args:
        SOURCE: centos:7
        SCAP_TARGET: stig-rhel7-disa
    # Variant: CentOS USGCB STIG
    baseline7-centos-usgcb:
      name: _env(PREFIX)baseline7-centos-usgcb:_env(TAG)
      context: baselines/baseline7
      dockerfile: Dockerfile
      args:
        SOURCE: centos:7
        SCAP_TARGET: ospp
      depends_on:
        # Ensure serial build
        - baseline7-centos-disa
    ## Platform: Security
    # Variant: OpenSCAP CentOS 7
    security-openscap7-centos:
      name: _env(PREFIX)security-openscap7-centos:_env(TAG)
      context: security/openscap7
      dockerfile: Dockerfile
      args:
        SOURCE: _env(PREFIX)baseline7-centos-disa:_env(TAG)
      depends_on:
        - baseline7-centos-disa