version: "3"

services:
  web:
    image: "${PREFIX:-civicactions/drydock-}drupal-pantheon-nginx:${TAG:-latest}"
    volumes:
      - .:/var/www
    depends_on:
      - php
  php:
    image: "${PREFIX:-civicactions/drydock-}drupal-pantheon-php-${VERSION:-7.2}:${TAG:-latest}"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
  mysql:
    image: "${PREFIX:-civicactions/drydock-}drupal-acquia-mysql:${TAG:-latest}"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
